// Command docgen-cli regenerates the Hugo CLI reference under
// website/content/docs/cli/ by walking the fiz Cobra command tree.
//
// Output:
//   - website/content/docs/cli/_index.md          (root command page)
//   - website/content/docs/cli/<dotted>.md        (per-subcommand pages)
//
// Run via `make docs-cli`. The generator is deterministic: re-running it
// without source changes produces byte-identical files.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/easel/fizeau/agentcli"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

func main() {
	out := flag.String("out", "website/content/docs/cli", "output directory for generated CLI docs")
	flag.Parse()

	root := agentcli.MountCLI()
	disableAutoGenTag(root)

	if err := os.MkdirAll(*out, 0o750); err != nil {
		fail(err)
	}
	if err := cleanGenerated(*out); err != nil {
		fail(err)
	}

	// Section landing page (Hextra reads _index.md as the section root).
	if err := writeIndex(*out, root); err != nil {
		fail(err)
	}

	// Per-command pages. We avoid cobra/doc.GenMarkdownTree because we want
	// custom front-matter and rewritten cross-links, but we still use
	// GenMarkdownCustom to render the body — keeping us aligned with cobra's
	// canonical formatting.
	pages := collectCommands(root)
	for _, c := range pages {
		if c == root {
			continue
		}
		if err := writeCommand(*out, root, c); err != nil {
			fail(err)
		}
	}
}

// disableAutoGenTag turns off cobra's "Auto generated by spf13/cobra on
// <date>" footer recursively. Without this the output churns daily, breaking
// idempotency.
func disableAutoGenTag(c *cobra.Command) {
	c.DisableAutoGenTag = true
	for _, child := range c.Commands() {
		disableAutoGenTag(child)
	}
}

// collectCommands returns root + every available descendant in deterministic
// (sorted) order.
func collectCommands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		out = append(out, c)
		children := append([]*cobra.Command(nil), c.Commands()...)
		sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
		for _, child := range children {
			if !child.IsAvailableCommand() || child.IsAdditionalHelpTopicCommand() {
				continue
			}
			walk(child)
		}
	}
	walk(root)
	return out
}

// slug converts "fiz catalog show" -> "fiz_catalog_show".
func slug(cmd *cobra.Command) string {
	return strings.ReplaceAll(cmd.CommandPath(), " ", "_")
}

// linkHandler rewrites cobra's "fiz_catalog.md" cross-links to Hextra-style
// relative refs. The root command's link points at the section index.
func linkHandler(rootSlug string) func(string) string {
	return func(s string) string {
		base := strings.TrimSuffix(s, ".md")
		if base == rootSlug {
			return "_index"
		}
		return base
	}
}

func writeIndex(dir string, root *cobra.Command) error {
	body := new(bytes.Buffer)
	if err := doc.GenMarkdownCustom(root, body, linkHandler(slug(root))); err != nil {
		return err
	}
	return writeFile(filepath.Join(dir, "_index.md"), frontMatter("CLI Reference", 3, "Every fiz subcommand and flag, generated from source."), body.Bytes())
}

func writeCommand(dir string, root, c *cobra.Command) error {
	body := new(bytes.Buffer)
	if err := doc.GenMarkdownCustom(c, body, linkHandler(slug(root))); err != nil {
		return err
	}
	title := strings.TrimPrefix(c.CommandPath(), root.Name()+" ")
	if title == "" {
		title = c.CommandPath()
	}
	return writeFile(filepath.Join(dir, slug(c)+".md"), frontMatter(title, 0, c.Short), body.Bytes())
}

// frontMatter builds Hextra-compatible TOML/YAML-style front matter. weight=0
// lets Hextra fall back to alphabetical ordering — fine for the CLI section.
func frontMatter(title string, weight int, description string) string {
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("title: " + yamlString(title) + "\n")
	if weight > 0 {
		fmt.Fprintf(&b, "weight: %d\n", weight)
	}
	if description != "" {
		b.WriteString("description: " + yamlString(description) + "\n")
	}
	b.WriteString("# Generated by `make docs-cli` — do not edit by hand.\n")
	b.WriteString("---\n\n")
	return b.String()
}

func yamlString(s string) string {
	// Quote to dodge YAML special chars ([, &, *, ?, |, >, !, %, @, `).
	return "\"" + strings.ReplaceAll(s, "\"", "\\\"") + "\""
}

func writeFile(path, frontMatter string, body []byte) error {
	buf := new(bytes.Buffer)
	buf.WriteString(frontMatter)
	buf.Write(body)
	return os.WriteFile(path, buf.Bytes(), 0o600)
}

// cleanGenerated wipes previously generated CLI pages so removed subcommands
// don't linger. We only touch *.md files and the _index.md at the section
// root, never traversing into unrelated subdirs.
func cleanGenerated(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			return err
		}
	}
	return nil
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "docgen-cli:", err)
	os.Exit(1)
}
