// Command docgen-adrs republishes ADRs from docs/helix/02-design/adr/ into
// website/content/docs/architecture/adr/ with Hextra-compatible front matter.
// Skips Superseded/Rejected. Output is byte-stable across runs. See `make docs-adrs`.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

const (
	defaultSrc = "docs/helix/02-design/adr"
	defaultOut = "website/content/docs/architecture/adr"
)

var (
	titleRe      = regexp.MustCompile(`^#\s+(ADR-\d+):\s*(.+?)\s*$`)
	titleStripRe = regexp.MustCompile(`(?m)^#\s+ADR-\d+:.*\n`)
	frontMatRe   = regexp.MustCompile(`(?s)^---\n.*?\n---\n`)
)

type adr struct {
	ID, Title, Status, Date, Summary, BodyNoFM, SourceFile string
	Num                                                    int
}

func main() {
	src := flag.String("src", defaultSrc, "source ADR directory")
	out := flag.String("out", defaultOut, "output directory")
	flag.Parse()
	entries, err := os.ReadDir(*src)
	if err != nil {
		fail(err)
	}
	var adrs []adr
	for _, e := range entries {
		n := e.Name()
		if !strings.HasPrefix(n, "ADR-") || !strings.HasSuffix(n, ".md") {
			continue
		}
		raw, err := os.ReadFile(filepath.Join(*src, n)) // #nosec G304 -- fixed in-repo ADR source dir, n filtered by HasPrefix/HasSuffix above
		if err != nil {
			fail(err)
		}
		a, err := parseADR(n, string(raw))
		if err != nil {
			fail(fmt.Errorf("%s: %w", n, err))
		}
		s := strings.ToLower(a.Status)
		if strings.HasPrefix(s, "superseded") || strings.HasPrefix(s, "rejected") {
			continue
		}
		adrs = append(adrs, a)
	}
	sort.Slice(adrs, func(i, j int) bool { return adrs[i].Num < adrs[j].Num })
	if err := os.MkdirAll(*out, 0o750); err != nil {
		fail(err)
	}
	stale, _ := filepath.Glob(filepath.Join(*out, "ADR-*.md"))
	for _, p := range stale {
		_ = os.Remove(p)
	}
	for i, a := range adrs {
		if err := os.WriteFile(filepath.Join(*out, a.ID+".md"), []byte(renderADR(a, i+2)), 0o600); err != nil {
			fail(err)
		}
	}
	if err := os.WriteFile(filepath.Join(*out, "_index.md"), []byte(renderIndex(adrs)), 0o600); err != nil {
		fail(err)
	}
}

func parseADR(filename, raw string) (adr, error) {
	body := frontMatRe.ReplaceAllString(raw, "")
	a := adr{SourceFile: filename, BodyNoFM: body}
	var contextLines, decisionLines []string
	var contextProblem string
	var inMeta, metaSep, inContext, inDecision bool
	for _, line := range strings.Split(body, "\n") {
		if a.Title == "" {
			if m := titleRe.FindStringSubmatch(line); m != nil {
				a.ID, a.Title = m[1], m[2]
				_, _ = fmt.Sscanf(strings.TrimPrefix(a.ID, "ADR-"), "%d", &a.Num)
				continue
			}
		}
		if a.Title != "" && a.Date == "" {
			switch {
			case strings.HasPrefix(line, "| Date"):
				inMeta = true
				continue
			case inMeta && !metaSep && strings.HasPrefix(line, "|---"):
				metaSep = true
				continue
			case inMeta && metaSep && strings.HasPrefix(line, "|"):
				if cells := splitTableRow(line); len(cells) >= 2 {
					a.Date, a.Status = cells[0], cells[1]
				}
				inMeta = false
				continue
			}
		}
		switch {
		case strings.HasPrefix(line, "## Context"):
			inContext, inDecision = true, false
			continue
		case strings.HasPrefix(line, "## Decision"):
			inContext, inDecision = false, true
			continue
		}
		if !inContext && !inDecision {
			continue
		}
		t := strings.TrimSpace(line)
		out := &decisionLines
		if inContext {
			out = &contextLines
		}
		if t == "" {
			if len(*out) > 0 {
				inContext, inDecision = false, false
			}
			continue
		}
		if strings.HasPrefix(t, "|") {
			if inContext && contextProblem == "" {
				if cells := splitTableRow(t); len(cells) >= 2 && strings.EqualFold(cells[0], "Problem") {
					contextProblem = cells[1]
				}
			}
			continue
		}
		if strings.HasPrefix(t, "###") {
			continue
		}
		*out = append(*out, t)
	}
	if a.Title == "" {
		return a, fmt.Errorf("no `# ADR-NNN: Title` heading")
	}
	pick := contextLines
	if len(pick) == 0 {
		if contextProblem != "" {
			pick = []string{contextProblem}
		} else {
			pick = decisionLines
		}
	}
	a.Summary = firstSentence(strings.Join(pick, " "))
	return a, nil
}

func splitTableRow(line string) []string {
	parts := strings.Split(strings.Trim(line, "| \t"), "|")
	for i, p := range parts {
		parts[i] = strings.TrimSpace(p)
	}
	return parts
}

func firstSentence(s string) string {
	if s = strings.TrimSpace(s); s == "" {
		return ""
	}
	if i := strings.Index(s, ". "); i > 0 {
		return s[:i+1]
	}
	if !strings.HasSuffix(s, ".") {
		s += "."
	}
	return s
}

func renderADR(a adr, weight int) string {
	body := strings.TrimLeft(titleStripRe.ReplaceAllString(a.BodyNoFM, ""), "\n")
	desc := strings.ReplaceAll(a.Summary, `"`, `\"`)
	return fmt.Sprintf(`---
title: "%s: %s"
linkTitle: "%s"
weight: %d
description: "%s"
# Generated by `+"`make docs-adrs`"+` from %s — do not edit by hand.
---

%s`, a.ID, a.Title, a.ID, weight, desc, a.SourceFile, body)
}

func renderIndex(adrs []adr) string {
	var b strings.Builder
	b.WriteString("---\ntitle: \"Architecture Decision Records\"\nlinkTitle: \"ADR Index\"\nweight: 1\ndescription: \"Numbered, dated decisions about Fizeau's architecture.\"\n# Generated by `make docs-adrs` — do not edit by hand.\n---\n\nEach ADR captures one architectural decision: the context that forced the\nchoice, the alternatives considered, what was decided, and the consequences.\nADRs are append-only — superseded entries stay in the source tree but are\nhidden from this index.\n\n| ADR | Status | Date | Decision |\n|-----|--------|------|----------|\n")
	for _, a := range adrs {
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s | %s |\n",
			a.ID, a.ID, a.Status, a.Date, strings.ReplaceAll(a.Title, "|", `\|`))
	}
	return b.String()
}

func fail(err error) { fmt.Fprintln(os.Stderr, "docgen-adrs:", err); os.Exit(1) }
