#!/usr/bin/env python3
"""Offline generator for the 1024 anchor word list.

Reads /usr/share/dict/words; keeps 6-12 char capital-first ASCII words; drops
Go keywords / predeclared identifiers; retains only words that encode to
exactly one token in BOTH OpenAI's cl100k_base BPE and a Llama-3 BPE
tokenizer; emits the first 1024 alphabetically as words.go.

Run from the package directory:
    python3 generate.py > words.go
"""
import sys
import tiktoken
from tokenizers import Tokenizer

GO_KEYWORDS = {
    "Break", "Case", "Chan", "Const", "Continue", "Default", "Defer",
    "Else", "Fallthrough", "For", "Func", "Goto", "If", "Import",
    "Interface", "Map", "Package", "Range", "Return", "Select",
    "Struct", "Switch", "Type", "Var",
}

GO_PREDECLARED = {
    "True", "False", "Nil", "Iota", "Append", "Cap", "Close", "Complex",
    "Copy", "Delete", "Imag", "Len", "Make", "New", "Panic", "Print",
    "Println", "Real", "Recover", "String", "Error", "Bool", "Byte",
    "Rune", "Float", "Uint", "Uintptr",
}

EXCLUDE = GO_KEYWORDS | GO_PREDECLARED

LLAMA_BOS = 128000


def main():
    cl = tiktoken.get_encoding("cl100k_base")
    llama = Tokenizer.from_pretrained("unsloth/llama-3-8b")

    with open("/usr/share/dict/words", encoding="utf-8") as f:
        raw = [w.strip() for w in f if w.strip()]

    cands = sorted({
        w[0].upper() + w[1:].lower()
        for w in raw
        if w.isascii() and w.isalpha() and 6 <= len(w) <= 12
    })
    cands = [w for w in cands if w not in EXCLUDE]

    keep = []
    for w in cands:
        if len(cl.encode(w)) != 1:
            continue
        ids = [i for i in llama.encode(w).ids if i != LLAMA_BOS]
        if len(ids) != 1:
            continue
        keep.append(w)

    print(f"single-token in both tokenizers: {len(keep)}", file=sys.stderr)
    if len(keep) < 1024:
        sys.exit(f"only {len(keep)} candidates; need 1024")

    final = keep[:1024]
    assert len(set(final)) == 1024
    assert all(6 <= len(w) <= 12 and w[0].isupper() for w in final)
    assert not (set(final) & EXCLUDE)

    out = sys.stdout
    out.write("// Code generated by internal/tool/anchorwords/generate.py; DO NOT EDIT.\n\n")
    out.write("// Package anchorwords provides the static 1024-word anchor vocabulary\n")
    out.write("// used by the ReadTool's anchor mode and the anchor_edit tool. Each entry\n")
    out.write("// is a 6-12 character capital-first English word that encodes to exactly\n")
    out.write("// one token in both the cl100k_base BPE (OpenAI) and a Llama-3 BPE.\n")
    out.write("package anchorwords\n\n")
    out.write("// Anchors is the fixed list of 1024 single-token anchor words.\n")
    out.write("// Indexing: line index i (0-based) maps to Anchors[i % 1024].\n")
    out.write("var Anchors = [1024]string{\n")
    per_line = 4
    for i in range(0, len(final), per_line):
        chunk = final[i : i + per_line]
        out.write("\t" + ", ".join(f'"{w}"' for w in chunk) + ",\n")
    out.write("}\n")


if __name__ == "__main__":
    main()
