package perf

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// WriteReports persists the given MatrixReport as both a human-readable
// markdown file (<dir>/<date>-baseline.md) and a machine-readable JSON sibling
// (<dir>/<date>-baseline.json). The JSON form is what a follow-up bead will
// diff in CI; the markdown is what humans read in the repo. A regression
// check (+25% on p95) is explicitly NOT wired here — the harness is the
// measurement surface, CI gating is tracked separately (ddx-9ce6842a AC §7).
func WriteReports(dir, date string, report MatrixReport) (mdPath, jsonPath string, err error) {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", "", fmt.Errorf("perf: mkdir %s: %w", dir, err)
	}
	if date == "" {
		date = "baseline"
	}
	jsonPath = filepath.Join(dir, date+"-baseline.json")
	data, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return "", "", fmt.Errorf("perf: marshal report: %w", err)
	}
	if err := os.WriteFile(jsonPath, data, 0o644); err != nil {
		return "", "", fmt.Errorf("perf: write %s: %w", jsonPath, err)
	}

	mdPath = filepath.Join(dir, date+"-baseline.md")
	if err := os.WriteFile(mdPath, []byte(renderMarkdown(report)), 0o644); err != nil {
		return "", "", fmt.Errorf("perf: write %s: %w", mdPath, err)
	}
	return mdPath, jsonPath, nil
}

func renderMarkdown(r MatrixReport) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "# GraphQL perf baseline — %s\n\n", r.GeneratedAt)
	fmt.Fprintf(&sb, "Generated by the `cli/internal/server/perf` harness (ddx-9ce6842a).\n\n")
	fmt.Fprintf(&sb, "## Fixture\n\n")
	fmt.Fprintf(&sb, "- Projects: %d\n", r.Fixture.Projects)
	fmt.Fprintf(&sb, "- Beads per project: %d\n", r.Fixture.BeadsPerProject)
	fmt.Fprintf(&sb, "- Total beads: %d\n", r.Fixture.TotalBeads)
	fmt.Fprintf(&sb, "- Agent sessions per project: %d\n\n", r.Fixture.AgentSessionsPerProject)

	fmt.Fprintf(&sb, "## Environment\n\n")
	fmt.Fprintf(&sb, "`%s`\n\n", r.Environment)

	fmt.Fprintf(&sb, "## Results (milliseconds)\n\n")
	fmt.Fprintf(&sb, "| Target | iter | in-proc p50 | in-proc p95 | in-proc p99 | HTTP p50 | HTTP p95 | HTTP p99 |\n")
	fmt.Fprintf(&sb, "|---|---:|---:|---:|---:|---:|---:|---:|\n")

	rows := make([]Result, len(r.Targets))
	copy(rows, r.Targets)
	sort.Slice(rows, func(i, j int) bool { return rows[i].Name < rows[j].Name })
	for _, row := range rows {
		httpP50, httpP95, httpP99 := "-", "-", "-"
		if row.HTTP != nil {
			httpP50 = fmt.Sprintf("%.2f", row.HTTP.P50)
			httpP95 = fmt.Sprintf("%.2f", row.HTTP.P95)
			httpP99 = fmt.Sprintf("%.2f", row.HTTP.P99)
		}
		fmt.Fprintf(&sb, "| `%s` | %d | %.2f | %.2f | %.2f | %s | %s | %s |\n",
			row.Name, row.Iterations,
			row.InProcess.P50, row.InProcess.P95, row.InProcess.P99,
			httpP50, httpP95, httpP99,
		)
	}
	fmt.Fprintf(&sb, "\n")

	fmt.Fprintf(&sb, "## Targets covered\n\n")
	fmt.Fprintf(&sb, "- `bead(id:)` — single-bead detail (shared with ddx-ad0db8fd).\n")
	fmt.Fprintf(&sb, "- `beadsByProject` — scoped list, default filter.\n")
	fmt.Fprintf(&sb, "- `beadsByProject_statusOpen` — scoped list with status filter pushdown.\n")
	fmt.Fprintf(&sb, "- `beads` (cross-project) — all-projects feed; worst-case scan.\n")
	fmt.Fprintf(&sb, "- `docGraph` — workspace doc graph build.\n")
	fmt.Fprintf(&sb, "- `agentSessions` — sessions.jsonl aggregation (shared with ddx-2ceb02fa).\n\n")

	fmt.Fprintf(&sb, "## Thresholds (ddx-9ce6842a AC §5)\n\n")
	fmt.Fprintf(&sb, "Targets on the default fixture (10 projects × 500 beads = 5,000 beads total):\n\n")
	fmt.Fprintf(&sb, "- `bead(id:)` p95 ≤ 50 ms in-process / ≤ 200 ms HTTP.\n")
	fmt.Fprintf(&sb, "- `beadsByProject(first=50)` p95 ≤ 75 ms in-process / ≤ 250 ms HTTP.\n")
	fmt.Fprintf(&sb, "- `beads(first=50)` p95 ≤ 200 ms in-process / ≤ 500 ms HTTP.\n\n")
	fmt.Fprintf(&sb, "If the scope-fix + filter-pushdown (Part 2 steps 1 and 2) do not meet these,\n")
	fmt.Fprintf(&sb, "the next step is the lightweight in-memory index (Part 2 step 3). The 2026-04-22\n")
	fmt.Fprintf(&sb, "user directive also keeps a real data store (axon / sqlite / postgres) on the\n")
	fmt.Fprintf(&sb, "table — that decision is raised to the user, not chosen unilaterally.\n\n")

	fmt.Fprintf(&sb, "## CI posture\n\n")
	fmt.Fprintf(&sb, "`make bench-graphql` regenerates this report. A +25%% p95 regression gate\n")
	fmt.Fprintf(&sb, "is proposed as a follow-up bead — the harness records thresholds here and\n")
	fmt.Fprintf(&sb, "in the JSON sibling so that gate can compare generations without re-running\n")
	fmt.Fprintf(&sb, "the full matrix against live code.\n")

	return sb.String()
}
