// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

// Node is the Relay global object identification interface
type Node interface {
	IsNode()
	// Globally unique identifier
	GetID() string
}

// AgentSession represents one agent execution session
type AgentSession struct {
	// Unique session identifier
	ID string `json:"id"`
	// Project this session belongs to
	ProjectID string `json:"projectId"`
	// Bead being worked on (null for ad-hoc runs)
	BeadID *string `json:"beadId,omitempty"`
	// Worker that produced this session, when known
	WorkerID *string `json:"workerId,omitempty"`
	// Agent harness used (e.g. "claude", "codex")
	Harness string `json:"harness"`
	// Model identifier
	Model string `json:"model"`
	// Effort level applied
	Effort string `json:"effort"`
	// Session status (e.g. "running", "completed", "failed")
	Status string `json:"status"`
	// When the session started
	StartedAt string `json:"startedAt"`
	// When the session ended (null if still running)
	EndedAt *string `json:"endedAt,omitempty"`
	// Path to stdout log file
	StdoutPath *string `json:"stdoutPath,omitempty"`
	// Path to stderr log file
	StderrPath *string `json:"stderrPath,omitempty"`
	// Total duration in milliseconds
	DurationMs int `json:"durationMs"`
	// Estimated cost in USD (null if unknown)
	Cost *float64 `json:"cost,omitempty"`
	// Cost-basis bucket for this session: paid, subscription, or local
	BillingMode string `json:"billingMode"`
	// Token consumption breakdown
	Tokens *TokenUsage `json:"tokens,omitempty"`
	// Outcome classification (e.g. "success", "failure")
	Outcome *string `json:"outcome,omitempty"`
	// Human-readable outcome detail
	Detail *string `json:"detail,omitempty"`
	// Git revision produced by this session
	ResultRev *string `json:"resultRev,omitempty"`
	// Git revision the session started from
	BaseRev *string `json:"baseRev,omitempty"`
	// Prompt body, loaded only for agentSession(id:)
	Prompt *string `json:"prompt,omitempty"`
	// Response body, loaded only for agentSession(id:)
	Response *string `json:"response,omitempty"`
	// Standard error body, loaded only for agentSession(id:)
	Stderr *string `json:"stderr,omitempty"`
}

func (AgentSession) IsNode() {}

// Globally unique identifier
func (this AgentSession) GetID() string { return this.ID }

// AgentSessionConnection is a Relay cursor connection of agent sessions
type AgentSessionConnection struct {
	// Ordered list of session edges
	Edges []*AgentSessionEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of sessions matching the filter
	TotalCount int `json:"totalCount"`
}

// AgentSessionEdge is one edge in an AgentSessionConnection
type AgentSessionEdge struct {
	// The session at this position
	Node *AgentSession `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// AggregateSummary is the full process-metrics summary
type AggregateSummary struct {
	// Bead-level aggregate counts
	Beads *AggregateSummaryBeads `json:"beads"`
	// Session-level aggregate counts
	Sessions *AggregateSummarySessions `json:"sessions"`
	// Cost aggregates
	Cost *AggregateSummaryCost `json:"cost"`
	// Cycle time aggregates
	CycleTime *AggregateSummaryCycleTime `json:"cycleTime"`
	// Rework aggregates
	Rework *AggregateSummaryRework `json:"rework"`
}

// AggregateSummaryBeads holds bead-level aggregate counts
type AggregateSummaryBeads struct {
	// Total number of beads
	Total int `json:"total"`
	// Number of beads in open status
	Open int `json:"open"`
	// Number of beads currently in progress
	InProgress int `json:"inProgress"`
	// Number of closed beads
	Closed int `json:"closed"`
	// Number of beads that have been reopened
	Reopened int `json:"reopened"`
	// Beads with known cycle time data
	KnownCycleTime int `json:"knownCycleTime"`
	// Beads with unknown cycle time data
	UnknownCycleTime int `json:"unknownCycleTime"`
	// Beads with known cost data
	KnownCost int `json:"knownCost"`
	// Beads with estimated cost data
	EstimatedCost int `json:"estimatedCost"`
	// Beads with unknown cost data
	UnknownCost int `json:"unknownCost"`
}

// AggregateSummaryCost holds cost aggregates across beads and features
type AggregateSummaryCost struct {
	// Number of beads with cost data
	Beads int `json:"beads"`
	// Number of features with cost data
	Features int `json:"features"`
	// Total known cost in USD
	KnownCostUsd float64 `json:"knownCostUsd"`
	// Total estimated cost in USD
	EstimatedCostUsd float64 `json:"estimatedCostUsd"`
	// Number of beads with no cost data
	UnknownBeads int `json:"unknownBeads"`
}

// AggregateSummaryCycleTime holds cycle time aggregates
type AggregateSummaryCycleTime struct {
	// Number of beads with known cycle time
	KnownCount int `json:"knownCount"`
	// Number of beads with unknown cycle time
	UnknownCount int `json:"unknownCount"`
	// Average cycle time in milliseconds
	AverageMs *int `json:"averageMs,omitempty"`
	// Minimum cycle time in milliseconds
	MinMs *int `json:"minMs,omitempty"`
	// Maximum cycle time in milliseconds
	MaxMs *int `json:"maxMs,omitempty"`
}

// AggregateSummaryRework holds rework/churn aggregates
type AggregateSummaryRework struct {
	// Number of beads with known closure data
	KnownClosed int `json:"knownClosed"`
	// Number of beads known to have been reopened
	KnownReopened int `json:"knownReopened"`
	// Number of beads with unknown rework data
	UnknownCount int `json:"unknownCount"`
	// Ratio of reopened to total closed beads
	ReopenRate float64 `json:"reopenRate"`
	// Total number of post-close revisions
	RevisionCount int `json:"revisionCount"`
}

// AggregateSummarySessions holds session-level aggregate counts
type AggregateSummarySessions struct {
	// Total number of sessions
	Total int `json:"total"`
	// Sessions correlated to a bead
	Correlated int `json:"correlated"`
	// Sessions not correlated to any bead
	Uncorrelated int `json:"uncorrelated"`
	// Total prompt/input tokens consumed
	InputTokens int `json:"inputTokens"`
	// Total completion/output tokens generated
	OutputTokens int `json:"outputTokens"`
	// Total tokens (input + output)
	TotalTokens int `json:"totalTokens"`
	// Sessions with known cost data
	KnownCost int `json:"knownCost"`
	// Sessions with estimated cost data
	EstimatedCost int `json:"estimatedCost"`
	// Sessions with unknown cost data
	UnknownCost int `json:"unknownCost"`
	// Total cost in USD
	CostUsd float64 `json:"costUsd"`
}

// Bead is a portable work item with lifecycle metadata
type Bead struct {
	// Unique bead identifier (e.g. "ddx-a1b2c3d4")
	ID string `json:"id"`
	// Short summary of the work
	Title string `json:"title"`
	// Lifecycle status: open, in-progress, closed, blocked
	Status string `json:"status"`
	// Numeric priority (lower is higher priority)
	Priority int `json:"priority"`
	// Issue classification (e.g. "task", "bug", "spike")
	IssueType string `json:"issueType"`
	// Agent or human currently responsible
	Owner *string `json:"owner,omitempty"`
	// When the bead was created
	CreatedAt string `json:"createdAt"`
	// Who or what created the bead
	CreatedBy *string `json:"createdBy,omitempty"`
	// Last modification timestamp
	UpdatedAt string `json:"updatedAt"`
	// Freeform labels for filtering and grouping
	Labels []string `json:"labels,omitempty"`
	// Project identifier this bead belongs to
	ProjectID *string `json:"projectID,omitempty"`
	// Parent bead ID for hierarchy
	Parent *string `json:"parent,omitempty"`
	// Full description / body text
	Description *string `json:"description,omitempty"`
	// Acceptance criteria text
	Acceptance *string `json:"acceptance,omitempty"`
	// Freeform notes appended during work
	Notes *string `json:"notes,omitempty"`
	// Dependency edges to other beads
	Dependencies []*Dependency `json:"dependencies,omitempty"`
}

func (Bead) IsNode() {}

// Globally unique identifier
func (this Bead) GetID() string { return this.ID }

// BeadConnection is a Relay cursor connection of beads
type BeadConnection struct {
	// Ordered list of bead edges
	Edges []*BeadEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of beads matching the filter
	TotalCount int `json:"totalCount"`
}

// BeadCostRow is one bead's cost attribution within a CostReport
type BeadCostRow struct {
	// Bead identifier
	BeadID string `json:"beadId"`
	// Bead title
	Title string `json:"title"`
	// Spec/feature ID the bead belongs to
	SpecID *string `json:"specId,omitempty"`
	// Current bead status
	Status string `json:"status"`
	// Agent sessions contributing to this bead's cost
	SessionIds []string `json:"sessionIds,omitempty"`
	// Total prompt/input tokens consumed
	InputTokens int `json:"inputTokens"`
	// Total completion/output tokens generated
	OutputTokens int `json:"outputTokens"`
	// Total tokens (input + output)
	TotalTokens int `json:"totalTokens"`
	// Cost data quality: known, estimated, or unknown
	CostState string `json:"costState"`
	// Cost in USD (null if unknown)
	CostUsd *float64 `json:"costUsd,omitempty"`
	// Number of sessions with unknown cost
	UnknownSessions *int `json:"unknownSessions,omitempty"`
	// Source references for cost attribution
	Provenance []*SourceRef `json:"provenance,omitempty"`
}

// BeadEdge is one edge in a BeadConnection
type BeadEdge struct {
	// The bead at this position
	Node *Bead `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// BeadEvent is an immutable execution evidence entry from the bead store
type BeadEvent struct {
	// Unique event identifier (bead ID + sequence)
	EventID string `json:"eventID"`
	// Bead ID that emitted this event
	BeadID string `json:"beadID"`
	// Event kind (e.g. "claim", "unclaim", "reopen", "summary")
	Kind string `json:"kind"`
	// Human-readable summary of the event
	Summary *string `json:"summary,omitempty"`
	// Full body text (e.g. agent output, metadata changes)
	Body *string `json:"body,omitempty"`
	// Actor that triggered this event (agent name or human name)
	Actor *string `json:"actor,omitempty"`
	// Timestamp of the event
	Timestamp string `json:"timestamp"`
}

// Input type for creating a new bead
type BeadInput struct {
	// Short summary of the work
	Title string `json:"title"`
	// Lifecycle status (default: "open")
	Status *string `json:"status,omitempty"`
	// Numeric priority (default: 2)
	Priority *int `json:"priority,omitempty"`
	// Issue classification (e.g. "task", "bug")
	IssueType *string `json:"issueType,omitempty"`
	// Freeform labels for filtering and grouping
	Labels []string `json:"labels,omitempty"`
	// Parent bead ID for hierarchy
	Parent *string `json:"parent,omitempty"`
	// Full description / body text
	Description *string `json:"description,omitempty"`
	// Acceptance criteria text
	Acceptance *string `json:"acceptance,omitempty"`
	// Freeform notes appended during work
	Notes *string `json:"notes,omitempty"`
}

// BeadStatusCounts holds aggregate bead counts by status
type BeadStatusCounts struct {
	// Number of beads in open status
	Open int `json:"open"`
	// Number of beads in closed status
	Closed int `json:"closed"`
	// Number of beads with unclosed dependencies
	Blocked int `json:"blocked"`
	// Number of open beads whose dependencies are all closed
	Ready int `json:"ready"`
	// Total number of beads
	Total int `json:"total"`
}

// Input type for updating an existing bead
type BeadUpdateInput struct {
	// Short summary of the work
	Title *string `json:"title,omitempty"`
	// Lifecycle status
	Status *string `json:"status,omitempty"`
	// Numeric priority
	Priority *int `json:"priority,omitempty"`
	// Issue classification
	IssueType *string `json:"issueType,omitempty"`
	// Freeform labels for filtering and grouping
	Labels []string `json:"labels,omitempty"`
	// Parent bead ID for hierarchy
	Parent *string `json:"parent,omitempty"`
	// Full description / body text
	Description *string `json:"description,omitempty"`
	// Acceptance criteria text
	Acceptance *string `json:"acceptance,omitempty"`
	// Freeform notes appended during work
	Notes *string `json:"notes,omitempty"`
}

// Commit represents a git commit
type Commit struct {
	// Full SHA hash
	Sha string `json:"sha"`
	// Abbreviated SHA (7 characters)
	ShortSha string `json:"shortSha"`
	// Author name and email
	Author string `json:"author"`
	// Commit timestamp
	Date string `json:"date"`
	// First line of the commit message
	Subject string `json:"subject"`
	// Remaining commit message body (null if single-line message)
	Body *string `json:"body,omitempty"`
	// Bead IDs referenced in the commit message
	BeadRefs []string `json:"beadRefs,omitempty"`
}

// CommitConnection is a Relay cursor connection of commits
type CommitConnection struct {
	// Ordered list of commit edges
	Edges []*CommitEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of commits matching the filter
	TotalCount int `json:"totalCount"`
}

// CommitEdge is one edge in a CommitConnection
type CommitEdge struct {
	// The commit at this position
	Node *Commit `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// ComparisonArmInput is one requested comparison arm.
type ComparisonArmInput struct {
	// Agent harness
	Harness *string `json:"harness,omitempty"`
	// Provider name
	Provider *string `json:"provider,omitempty"`
	// Model identifier
	Model string `json:"model"`
	// Prompt or task text
	Prompt string `json:"prompt"`
}

// ComparisonDispatchResult describes a queued model comparison.
type ComparisonDispatchResult struct {
	// Comparison identifier
	ID string `json:"id"`
	// Queued/running state
	State string `json:"state"`
	// Number of configured arms
	ArmCount int `json:"armCount"`
}

// ComparisonRecord is a queued or completed model comparison.
type ComparisonRecord struct {
	// Comparison identifier
	ID string `json:"id"`
	// Comparison state
	State string `json:"state"`
	// Number of configured arms
	ArmCount int `json:"armCount"`
}

// ComparisonResult records a metric comparison against a baseline
type ComparisonResult struct {
	// Baseline value being compared against
	Baseline float64 `json:"baseline"`
	// Absolute difference (observed - baseline)
	Delta float64 `json:"delta"`
	// Direction of change ("better", "worse", "neutral")
	Direction string `json:"direction"`
}

// CoordinatorMetrics holds outcome metrics for one land coordinator
type CoordinatorMetrics struct {
	// Number of submissions successfully merged
	Landed int `json:"landed"`
	// Number of submissions kept in a separate worktree
	Preserved int `json:"preserved"`
	// Number of submissions that failed
	Failed int `json:"failed"`
	// Number of submissions that failed to push
	PushFailed int `json:"pushFailed"`
	// Sum of all submission durations in milliseconds
	TotalDurationMs int `json:"totalDurationMs"`
	// Total commits across all submissions
	TotalCommits int `json:"totalCommits"`
	// Ratio of preserved+failed to total submissions
	PreservedRatio float64 `json:"preservedRatio"`
	// Up to the last 10 submission outcomes
	LastSubmissions []*LandOutcomeSummary `json:"lastSubmissions,omitempty"`
}

// CoordinatorMetricsEntry pairs a project root with its coordinator metrics
type CoordinatorMetricsEntry struct {
	// Absolute path to the project root
	ProjectRoot string `json:"projectRoot"`
	// Coordinator outcome metrics for this project
	Metrics *CoordinatorMetrics `json:"metrics"`
}

// CoordinatorMetricsUpdate is a metrics snapshot from a land coordinator
type CoordinatorMetricsUpdate struct {
	// Unique update identifier
	UpdateID string `json:"updateID"`
	// Project root these metrics belong to
	ProjectRoot string `json:"projectRoot"`
	// Timestamp of the update
	Timestamp string `json:"timestamp"`
	// Number of submissions successfully merged
	Landed int `json:"landed"`
	// Number of submissions kept in a separate worktree
	Preserved int `json:"preserved"`
	// Number of submissions that failed
	Failed int `json:"failed"`
	// Number of submissions that failed to push
	PushFailed int `json:"pushFailed"`
	// Sum of all submission durations in milliseconds
	TotalDurationMs int `json:"totalDurationMs"`
	// Total commits across all submissions
	TotalCommits int `json:"totalCommits"`
}

// CostReport describes bead and feature cost attribution over a time window
type CostReport struct {
	// Report scope (e.g. "all", "bead", "feature")
	Scope string `json:"scope"`
	// Time window for the report (null means all-time)
	Window *Window `json:"window,omitempty"`
	// Filter: specific bead ID (null for all beads)
	BeadID *string `json:"beadId,omitempty"`
	// Filter: specific feature ID (null for all features)
	FeatureID *string `json:"featureId,omitempty"`
	// Per-bead cost rows
	Beads []*BeadCostRow `json:"beads,omitempty"`
	// Per-feature cost rows
	Features []*FeatureCostRow `json:"features,omitempty"`
	// Aggregate cost summary
	Summary *CostSummary `json:"summary"`
}

// CostSummary aggregates cost across all beads/features in a cost report
type CostSummary struct {
	// Number of beads with cost data
	Beads int `json:"beads"`
	// Number of features with cost data
	Features int `json:"features"`
	// Total known cost in USD
	KnownCostUsd float64 `json:"knownCostUsd"`
	// Total estimated cost in USD
	EstimatedCostUsd float64 `json:"estimatedCostUsd"`
	// Number of beads with no cost data
	UnknownBeads int `json:"unknownBeads"`
}

// CurrentAttemptInfo summarises the in-flight execution attempt
type CurrentAttemptInfo struct {
	// Unique attempt identifier
	AttemptID string `json:"attemptId"`
	// Bead being executed
	BeadID string `json:"beadId"`
	// Title of the bead being executed
	BeadTitle *string `json:"beadTitle,omitempty"`
	// Harness running this attempt
	Harness *string `json:"harness,omitempty"`
	// Model used for this attempt
	Model *string `json:"model,omitempty"`
	// Profile/configuration name
	Profile *string `json:"profile,omitempty"`
	// Current execution phase
	Phase string `json:"phase"`
	// Sequence number of the current phase
	PhaseSeq int `json:"phaseSeq"`
	// When this attempt started
	StartedAt string `json:"startedAt"`
	// Milliseconds elapsed since attempt start
	ElapsedMs int `json:"elapsedMs"`
}

// CycleTimeReport describes lifecycle timing over a time window
type CycleTimeReport struct {
	// Report scope
	Scope string `json:"scope"`
	// Time window for the report
	Window *Window `json:"window,omitempty"`
	// Per-bead cycle time rows
	Beads []*CycleTimeRow `json:"beads,omitempty"`
	// Aggregate cycle time summary
	Summary *CycleTimeSummary `json:"summary"`
}

// CycleTimeRow describes one bead's lifecycle timing
type CycleTimeRow struct {
	// Bead identifier
	BeadID string `json:"beadId"`
	// Bead title
	Title string `json:"title"`
	// Spec/feature ID the bead belongs to
	SpecID *string `json:"specId,omitempty"`
	// Current bead status
	Status string `json:"status"`
	// When the bead was created
	CreatedAt string `json:"createdAt"`
	// When the bead was first closed
	FirstClosedAt *string `json:"firstClosedAt,omitempty"`
	// When the bead was last closed
	LastClosedAt *string `json:"lastClosedAt,omitempty"`
	// Total cycle time in milliseconds (null if still open)
	CycleTimeMs *int `json:"cycleTimeMs,omitempty"`
	// Number of times the bead was reopened
	ReopenCount *int `json:"reopenCount,omitempty"`
	// Number of post-close revisions
	RevisionCount *int `json:"revisionCount,omitempty"`
	// Time spent in open status in milliseconds
	TimeInOpenMs *int `json:"timeInOpenMs,omitempty"`
	// Time spent in in-progress status in milliseconds
	TimeInProgressMs *int `json:"timeInProgressMs,omitempty"`
	// Time spent in closed status in milliseconds
	TimeInClosedMs *int `json:"timeInClosedMs,omitempty"`
	// Cycle time data quality: known, estimated, or unknown
	CycleState string `json:"cycleState"`
	// Source references for timing attribution
	Provenance []*SourceRef `json:"provenance,omitempty"`
}

// CycleTimeSummary aggregates lifecycle timing across all beads in a report
type CycleTimeSummary struct {
	// Number of beads with known cycle time
	KnownCount int `json:"knownCount"`
	// Number of beads with unknown cycle time
	UnknownCount int `json:"unknownCount"`
	// Average cycle time in milliseconds
	AverageMs *int `json:"averageMs,omitempty"`
	// Minimum cycle time in milliseconds
	MinMs *int `json:"minMs,omitempty"`
	// Maximum cycle time in milliseconds
	MaxMs *int `json:"maxMs,omitempty"`
}

// DefaultRouteStatus shows which provider/model the default model-ref resolves to.
type DefaultRouteStatus struct {
	// The model-ref key (e.g. "code-medium") or empty if no default configured
	ModelRef string `json:"modelRef"`
	// Selected provider name, or null if no healthy candidate found
	ResolvedProvider *string `json:"resolvedProvider,omitempty"`
	// Selected model identifier, or null if no healthy candidate found
	ResolvedModel *string `json:"resolvedModel,omitempty"`
	// Routing strategy (e.g. "first-available")
	Strategy *string `json:"strategy,omitempty"`
}

// Dependency is a directed edge between two beads
type Dependency struct {
	// The bead that has the dependency
	IssueID string `json:"issueId"`
	// The bead that must be completed first
	DependsOnID string `json:"dependsOnId"`
	// Dependency kind (e.g. "blocks", "relates-to")
	Type string `json:"type"`
	// When the dependency was created
	CreatedAt *string `json:"createdAt,omitempty"`
	// Who created the dependency
	CreatedBy *string `json:"createdBy,omitempty"`
	// Opaque metadata attached to the link
	Metadata *string `json:"metadata,omitempty"`
}

// DocGraph represents the full document dependency graph
type DocGraph struct {
	// Absolute path to the docgraph root directory
	RootDir string `json:"rootDir"`
	// All documents in the graph
	Documents []*Document `json:"documents"`
	// Map of relative paths to document IDs
	PathToID string `json:"pathToId"`
	// Map of document IDs to lists of dependent IDs
	Dependents string `json:"dependents"`
	// Warnings generated during graph construction. Derived from issues; prefer the structured issues field when rendering UI.
	Warnings []string `json:"warnings"`
	// Structured integrity issues for the graph, grouped by kind on the client.
	Issues []*GraphIssue `json:"issues"`
}

// Document represents a docgraph document with dependency tracking
type Document struct {
	// Document identifier (usually the relative path)
	ID string `json:"id"`
	// Filesystem path relative to the library root
	Path string `json:"path"`
	// Human-readable title extracted from frontmatter
	Title string `json:"title"`
	// IDs of documents this document depends on
	DependsOn []string `json:"dependsOn"`
	// IDs of input artifacts consumed by this document
	Inputs []string `json:"inputs"`
	// IDs of documents that depend on this document
	Dependents []string `json:"dependents"`
	// Review state metadata (null if never reviewed)
	Review *DocumentReview `json:"review,omitempty"`
	// True if parked (excluded from staleness checks)
	ParkingLot bool `json:"parkingLot"`
	// Prompt text embedded in the document frontmatter
	Prompt *string `json:"prompt,omitempty"`
	// Execution definition embedded in the document (null if none)
	ExecDef *DocumentExecDef `json:"execDef,omitempty"`
	// Raw file content (populated only by documentByPath, null in list queries)
	Content *string `json:"content,omitempty"`
}

func (Document) IsNode() {}

// Globally unique identifier
func (this Document) GetID() string { return this.ID }

// DocumentConnection is a Relay cursor connection of documents
type DocumentConnection struct {
	// Ordered list of document edges
	Edges []*DocumentEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of documents matching the filter
	TotalCount int `json:"totalCount"`
}

// DocumentEdge is one edge in a DocumentConnection
type DocumentEdge struct {
	// The document at this position
	Node *Document `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// DocumentExecDef holds an execution definition embedded in a document
type DocumentExecDef struct {
	// Definition identifier
	ID *string `json:"id,omitempty"`
	// IDs of artifacts this definition produces or consumes
	ArtifactIds []string `json:"artifactIds,omitempty"`
	// How to invoke the execution
	Executor *ExecutorSpec `json:"executor,omitempty"`
	// How to interpret the result
	Result *ResultSpec `json:"result,omitempty"`
	// Evaluation criteria and thresholds
	Evaluation *Evaluation `json:"evaluation,omitempty"`
	// Whether the definition is currently active
	Active *bool `json:"active,omitempty"`
	// Whether the definition must pass for merge
	Required *bool `json:"required,omitempty"`
	// Whether this definition was discovered from the docgraph
	GraphSource *bool `json:"graphSource,omitempty"`
	// When the definition was created
	CreatedAt *string `json:"createdAt,omitempty"`
}

// DocumentReview holds review-state metadata for a document
type DocumentReview struct {
	// Hash of the document content at review time
	SelfHash string `json:"selfHash"`
	// Map of dependency IDs to their hashes at review time
	Deps string `json:"deps"`
	// ISO-8601 timestamp of the last review
	ReviewedAt string `json:"reviewedAt"`
}

// EfficacyAttempt is one historical attempt for an efficacy row.
type EfficacyAttempt struct {
	// Bead identifier
	BeadID string `json:"beadId"`
	// Attempt outcome
	Outcome string `json:"outcome"`
	// Duration in milliseconds
	DurationMs int `json:"durationMs"`
	// Cost in USD when known
	CostUsd *float64 `json:"costUsd,omitempty"`
	// Execution evidence URL or path
	EvidenceBundleURL string `json:"evidenceBundleUrl"`
}

// EfficacyAttempts groups attempt details for a row.
type EfficacyAttempts struct {
	// Stable row key
	RowKey string `json:"rowKey"`
	// Attempts in newest-first order
	Attempts []*EfficacyAttempt `json:"attempts"`
}

// EfficacyRow summarizes agent performance for one harness/provider/model tuple.
type EfficacyRow struct {
	// Stable row key
	RowKey string `json:"rowKey"`
	// Agent harness
	Harness string `json:"harness"`
	// Provider name
	Provider string `json:"provider"`
	// Model identifier
	Model string `json:"model"`
	// Attempt count
	Attempts int `json:"attempts"`
	// Successful attempt count
	Successes int `json:"successes"`
	// Successes divided by attempts
	SuccessRate float64 `json:"successRate"`
	// Median input tokens
	MedianInputTokens int `json:"medianInputTokens"`
	// Median output tokens
	MedianOutputTokens int `json:"medianOutputTokens"`
	// Median duration in milliseconds
	MedianDurationMs int `json:"medianDurationMs"`
	// Median cost in USD when known
	MedianCostUsd *float64 `json:"medianCostUsd,omitempty"`
	// Optional warning metadata
	Warning *EfficacyWarning `json:"warning,omitempty"`
}

// EfficacyWarning flags a model row that needs operator attention.
type EfficacyWarning struct {
	// Warning kind
	Kind string `json:"kind"`
	// Numeric threshold involved in the warning
	Threshold *float64 `json:"threshold,omitempty"`
}

// Evaluation holds interpretation rules for execution results
type Evaluation struct {
	// Comparison operator (e.g. "lt", "gt", "eq")
	Comparison *string `json:"comparison,omitempty"`
	// Threshold values for warn/ratchet
	Thresholds *Thresholds `json:"thresholds,omitempty"`
}

// Execution represents one execute-bead attempt bundle stored under
// `.ddx/executions/<ts>-<hash>/`. It joins bead, session, prompt, verdict,
// and tool-call stream together as the canonical record of a single
// ddx agent execute-bead attempt.
type Execution struct {
	// Stable ID, equal to the bundle directory name (e.g. 20260423T002311-2ebaa669).
	ID string `json:"id"`
	// Project this execution belongs to.
	ProjectID string `json:"projectId"`
	// Linked bead ID (manifest.bead_id).
	BeadID *string `json:"beadId,omitempty"`
	// Bead title at the time the execution ran (when manifest carried it).
	BeadTitle *string `json:"beadTitle,omitempty"`
	// Linked session ID (result.session_id) if a session was recorded.
	SessionID *string `json:"sessionId,omitempty"`
	// Worker ID if recorded in the manifest.
	WorkerID *string `json:"workerId,omitempty"`
	// Harness used (e.g. claude, codex, agent).
	Harness *string `json:"harness,omitempty"`
	// Model identifier used.
	Model *string `json:"model,omitempty"`
	// Verdict / outcome reported in result.json (e.g. PASS, BLOCK, no_changes, success).
	Verdict *string `json:"verdict,omitempty"`
	// Status from result.json (success, failure, no_changes, etc.).
	Status *string `json:"status,omitempty"`
	// Human-readable rationale or detail from result.json.
	Rationale *string `json:"rationale,omitempty"`
	// When the bundle was created (manifest.created_at), ISO-8601.
	CreatedAt string `json:"createdAt"`
	// When the run started (result.started_at), ISO-8601.
	StartedAt *string `json:"startedAt,omitempty"`
	// When the run finished (result.finished_at), ISO-8601.
	FinishedAt *string `json:"finishedAt,omitempty"`
	// Total duration in milliseconds.
	DurationMs *int `json:"durationMs,omitempty"`
	// Estimated cost in USD.
	CostUsd *float64 `json:"costUsd,omitempty"`
	// Total token count (when reported).
	Tokens *int `json:"tokens,omitempty"`
	// Process exit code from the harness.
	ExitCode *int `json:"exitCode,omitempty"`
	// Git revision the attempt started from.
	BaseRev *string `json:"baseRev,omitempty"`
	// Git revision the attempt produced (commit SHA when one was made).
	ResultRev *string `json:"resultRev,omitempty"`
	// Bundle directory (relative to project root).
	BundlePath string `json:"bundlePath"`
	// Path to the prompt file in the bundle.
	PromptPath *string `json:"promptPath,omitempty"`
	// Path to the result file in the bundle.
	ResultPath *string `json:"resultPath,omitempty"`
	// Path to the manifest file in the bundle.
	ManifestPath *string `json:"manifestPath,omitempty"`
	// Path to the agent-log file (when known) carrying tool-call frames.
	AgentLogPath *string `json:"agentLogPath,omitempty"`
	// Prompt body (markdown). Loaded only for execution(id:).
	Prompt *string `json:"prompt,omitempty"`
	// Manifest JSON as a single string (raw). Loaded only for execution(id:).
	Manifest *string `json:"manifest,omitempty"`
	// Result JSON as a single string (raw). Loaded only for execution(id:).
	Result *string `json:"result,omitempty"`
}

func (Execution) IsNode() {}

// Globally unique identifier
func (this Execution) GetID() string { return this.ID }

// ExecutionConnection is a Relay cursor connection of executions.
type ExecutionConnection struct {
	// Ordered list of execution edges.
	Edges []*ExecutionEdge `json:"edges"`
	// Pagination metadata.
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of executions matching the filter.
	TotalCount int `json:"totalCount"`
}

// ExecutionDefinition describes a repeatable execution (check, benchmark, etc.)
type ExecutionDefinition struct {
	// Unique definition identifier
	ID string `json:"id"`
	// IDs of artifacts this definition produces or consumes
	ArtifactIds []string `json:"artifactIds"`
	// How to invoke the execution
	Executor *ExecutorSpec `json:"executor"`
	// How to interpret the result
	Result *ResultSpec `json:"result,omitempty"`
	// Evaluation criteria and thresholds
	Evaluation *Evaluation `json:"evaluation,omitempty"`
	// Whether the definition is currently active
	Active bool `json:"active"`
	// Whether the definition must pass for merge
	Required *bool `json:"required,omitempty"`
	// Whether this definition was discovered from the docgraph
	GraphSource *bool `json:"graphSource,omitempty"`
	// When the definition was created
	CreatedAt string `json:"createdAt"`
}

func (ExecutionDefinition) IsNode() {}

// Globally unique identifier
func (this ExecutionDefinition) GetID() string { return this.ID }

// ExecutionDefinitionConnection is a Relay cursor connection of execution definitions
type ExecutionDefinitionConnection struct {
	// Ordered list of definition edges
	Edges []*ExecutionDefinitionEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of definitions matching the filter
	TotalCount int `json:"totalCount"`
}

// ExecutionDefinitionEdge is one edge in an ExecutionDefinitionConnection
type ExecutionDefinitionEdge struct {
	// The definition at this position
	Node *ExecutionDefinition `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// ExecutionEdge is one edge in an ExecutionConnection.
type ExecutionEdge struct {
	// The execution at this position.
	Node *Execution `json:"node"`
	// Opaque cursor for pagination.
	Cursor string `json:"cursor"`
}

// ExecutionEvent is a log output from an execution run
type ExecutionEvent struct {
	// Unique event identifier (run ID + sequence)
	EventID string `json:"eventID"`
	// Run that emitted this event
	RunID string `json:"runID"`
	// Output stream (stdout or stderr)
	Stream string `json:"stream"`
	// Log line content
	Line string `json:"line"`
	// Timestamp of the event
	Timestamp string `json:"timestamp"`
}

// ExecutionRun represents one invocation of an execution definition
type ExecutionRun struct {
	// Unique run identifier
	ID string `json:"id"`
	// ID of the definition that was executed
	DefinitionID string `json:"definitionId"`
	// IDs of artifacts involved in this run
	ArtifactIds []string `json:"artifactIds"`
	// When the run started
	StartedAt string `json:"startedAt"`
	// When the run finished
	FinishedAt string `json:"finishedAt"`
	// Run outcome status (e.g. "pass", "fail", "error")
	Status string `json:"status"`
	// Process exit code
	ExitCode int `json:"exitCode"`
	// Whether a failure blocks merge
	MergeBlocking *bool `json:"mergeBlocking,omitempty"`
	// Correlated agent session ID (null if not agent-driven)
	AgentSessionID *string `json:"agentSessionId,omitempty"`
	// Opaque attachments (files, screenshots, etc.)
	Attachments *string `json:"attachments,omitempty"`
	// Host and version metadata for reproducibility
	Provenance *Provenance `json:"provenance,omitempty"`
	// Metric observation extracted from output (null if not metric-typed)
	Metric *MetricObservation `json:"metric,omitempty"`
	// Captured stdout from the execution
	Stdout *string `json:"stdout,omitempty"`
	// Captured stderr from the execution
	Stderr *string `json:"stderr,omitempty"`
	// Extracted numeric value (null if not parsed)
	Value *float64 `json:"value,omitempty"`
	// Unit of the extracted value
	Unit *string `json:"unit,omitempty"`
	// Whether the output was successfully parsed
	Parsed *bool `json:"parsed,omitempty"`
}

func (ExecutionRun) IsNode() {}

// Globally unique identifier
func (this ExecutionRun) GetID() string { return this.ID }

// ExecutionRunConnection is a Relay cursor connection of execution runs
type ExecutionRunConnection struct {
	// Ordered list of run edges
	Edges []*ExecutionRunEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of runs matching the filter
	TotalCount int `json:"totalCount"`
}

// ExecutionRunEdge is one edge in an ExecutionRunConnection
type ExecutionRunEdge struct {
	// The run at this position
	Node *ExecutionRun `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// ExecutionRunLog holds the captured output from an execution run
type ExecutionRunLog struct {
	// Captured standard output
	Stdout string `json:"stdout"`
	// Captured standard error
	Stderr string `json:"stderr"`
}

// ExecutionToolCall is one tool_use/tool_result pair in an execution's agent-log stream.
type ExecutionToolCall struct {
	// Stable index within the stream (used as cursor).
	ID string `json:"id"`
	// Tool name (e.g. Bash, Read, Write, Edit).
	Name string `json:"name"`
	// Sequence number within the stream, starting at 0.
	Seq int `json:"seq"`
	// Frame timestamp (ISO-8601), when present.
	Ts *string `json:"ts,omitempty"`
	// Tool input as a JSON-encoded string.
	Inputs *string `json:"inputs,omitempty"`
	// Tool output as a string. May be truncated for very large outputs.
	Output *string `json:"output,omitempty"`
	// Whether the output payload was truncated for transport.
	Truncated *bool `json:"truncated,omitempty"`
}

// ExecutionToolCallConnection is a Relay cursor connection of tool calls.
type ExecutionToolCallConnection struct {
	// Ordered list of tool call edges.
	Edges []*ExecutionToolCallEdge `json:"edges"`
	// Pagination metadata.
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of tool calls available in the stream.
	TotalCount int `json:"totalCount"`
}

// ExecutionToolCallEdge is one edge in an ExecutionToolCallConnection.
type ExecutionToolCallEdge struct {
	// The tool call at this position.
	Node *ExecutionToolCall `json:"node"`
	// Opaque cursor for pagination.
	Cursor string `json:"cursor"`
}

// ExecutorSpec describes how to invoke an execution
type ExecutorSpec struct {
	// Execution kind (e.g. "shell", "agent")
	Kind string `json:"kind"`
	// Command and arguments to run
	Command []string `json:"command,omitempty"`
	// Working directory for the command
	Cwd *string `json:"cwd,omitempty"`
	// Environment variables as key-value pairs
	Env *string `json:"env,omitempty"`
	// Maximum execution time in milliseconds
	TimeoutMs *int `json:"timeoutMs,omitempty"`
}

// FeatureCostRow aggregates bead cost rows by spec/feature ID
type FeatureCostRow struct {
	// Spec/feature identifier
	SpecID string `json:"specId"`
	// Bead IDs contributing to this feature's cost
	BeadIds []string `json:"beadIds,omitempty"`
	// Total prompt/input tokens consumed
	InputTokens int `json:"inputTokens"`
	// Total completion/output tokens generated
	OutputTokens int `json:"outputTokens"`
	// Total tokens (input + output)
	TotalTokens int `json:"totalTokens"`
	// Cost data quality: known, estimated, or unknown
	CostState string `json:"costState"`
	// Cost in USD (null if unknown)
	CostUsd *float64 `json:"costUsd,omitempty"`
	// Number of beads with unknown cost
	UnknownBeads *int `json:"unknownBeads,omitempty"`
}

// GraphIssue describes one integrity problem discovered while building the document graph.
type GraphIssue struct {
	// Machine-readable category (e.g. duplicate_id, missing_dep).
	Kind string `json:"kind"`
	// Path of the offending document, when known.
	Path *string `json:"path,omitempty"`
	// Document identifier associated with the issue, when known.
	ID *string `json:"id,omitempty"`
	// Human-readable explanation suitable for the UI or terminal.
	Message string `json:"message"`
	// Related document path (e.g. the pre-existing path a duplicate ID collides with).
	RelatedPath *string `json:"relatedPath,omitempty"`
}

// HealthStatus represents the server health response
type HealthStatus struct {
	// Status string ("ok" when healthy)
	Status string `json:"status"`
	// When the server process started
	StartedAt string `json:"startedAt"`
}

// LandOutcomeSummary is one entry in the coordinator's submission log
type LandOutcomeSummary struct {
	// When the submission completed
	Ts string `json:"ts"`
	// Bead ID that was submitted (null for non-bead work)
	BeadID *string `json:"beadId,omitempty"`
	// Attempt ID of the submission
	AttemptID *string `json:"attemptId,omitempty"`
	// Outcome: landed, preserved, failed, or push_failed
	Outcome string `json:"outcome"`
	// Duration of the land operation in milliseconds
	DurationMs int `json:"durationMs"`
	// Number of commits in the submission
	CommitCount int `json:"commitCount"`
}

// LastAttemptInfo summarises the most recently completed attempt
type LastAttemptInfo struct {
	// Unique attempt identifier
	AttemptID string `json:"attemptId"`
	// Bead that was executed
	BeadID string `json:"beadId"`
	// Final phase reached
	Phase string `json:"phase"`
	// When the attempt started
	StartedAt string `json:"startedAt"`
	// When the attempt ended
	EndedAt string `json:"endedAt"`
	// Total duration in milliseconds
	ElapsedMs int `json:"elapsedMs"`
}

// MetricObservation records a metric-shaped measurement from an execution
type MetricObservation struct {
	// Artifact ID the metric belongs to
	ArtifactID string `json:"artifactId"`
	// Definition ID that produced this metric
	DefinitionID string `json:"definitionId"`
	// When the observation was recorded
	ObservedAt string `json:"observedAt"`
	// Observation status (e.g. "pass", "warn", "fail")
	Status string `json:"status"`
	// Observed numeric value
	Value float64 `json:"value"`
	// Unit of measurement
	Unit *string `json:"unit,omitempty"`
	// Raw sample values (for distribution metrics)
	Samples []float64 `json:"samples,omitempty"`
	// Comparison against baseline (null if no baseline)
	Comparison *ComparisonResult `json:"comparison,omitempty"`
}

// MetricResultSpec defines metric extraction from execution output
type MetricResultSpec struct {
	// Unit of measurement (e.g. "ms", "bytes")
	Unit *string `json:"unit,omitempty"`
	// JSONPath to the numeric value
	ValuePath *string `json:"valuePath,omitempty"`
	// JSONPath to the samples array
	SamplesPath *string `json:"samplesPath,omitempty"`
}

// Mutation is the root entry point for all write operations
type Mutation struct {
}

// NodeInfo represents the running ddx-server instance
type NodeInfo struct {
	// Unique node identifier (stable across restarts)
	ID string `json:"id"`
	// Human-readable node name
	Name string `json:"name"`
	// Timestamp when the server process started
	StartedAt string `json:"startedAt"`
	// Timestamp of the most recent heartbeat
	LastSeen string `json:"lastSeen"`
}

func (NodeInfo) IsNode() {}

// Globally unique identifier
func (this NodeInfo) GetID() string { return this.ID }

// PageInfo carries cursor-based pagination state (Relay spec)
type PageInfo struct {
	// True when more edges exist after the last returned edge
	HasNextPage bool `json:"hasNextPage"`
	// True when more edges exist before the first returned edge
	HasPreviousPage bool `json:"hasPreviousPage"`
	// Cursor of the first edge in the current page (null when empty)
	StartCursor *string `json:"startCursor,omitempty"`
	// Cursor of the last edge in the current page (null when empty)
	EndCursor *string `json:"endCursor,omitempty"`
}

// PaletteActionResult is an executable action in the command palette.
type PaletteActionResult struct {
	Kind  string `json:"kind"`
	ID    string `json:"id"`
	Label string `json:"label"`
}

// PaletteBeadResult is a bead match for the command palette.
type PaletteBeadResult struct {
	Kind  string `json:"kind"`
	ID    string `json:"id"`
	Title string `json:"title"`
}

// PaletteDocumentResult is a document match for the command palette.
type PaletteDocumentResult struct {
	Kind  string `json:"kind"`
	Path  string `json:"path"`
	Title string `json:"title"`
}

// PaletteNavigationResult is a navigation target in the command palette.
type PaletteNavigationResult struct {
	Kind  string `json:"kind"`
	Route string `json:"route"`
	Title string `json:"title"`
}

// PaletteSearchResults groups command palette result buckets.
type PaletteSearchResults struct {
	Documents  []*PaletteDocumentResult   `json:"documents"`
	Beads      []*PaletteBeadResult       `json:"beads"`
	Actions    []*PaletteActionResult     `json:"actions"`
	Navigation []*PaletteNavigationResult `json:"navigation"`
}

// Persona represents an AI persona definition from the library
type Persona struct {
	// Unique persona identifier
	ID string `json:"id"`
	// Persona name (e.g. "strict-code-reviewer")
	Name string `json:"name"`
	// Roles this persona fulfills (e.g. ["code-reviewer"])
	Roles []string `json:"roles"`
	// Short description of the persona's behaviour
	Description string `json:"description"`
	// Freeform tags for discovery and filtering
	Tags []string `json:"tags"`
	// Full persona prompt/instruction text
	Content string `json:"content"`
	// Markdown body for frontend detail views
	Body string `json:"body"`
	// Persona source package or plugin
	Source string `json:"source"`
	// Known project bindings for this persona
	Bindings []*PersonaBinding `json:"bindings"`
	// Filesystem path to the persona definition file
	FilePath *string `json:"filePath,omitempty"`
	// Last modification time of the persona file
	ModTime *string `json:"modTime,omitempty"`
}

func (Persona) IsNode() {}

// Globally unique identifier
func (this Persona) GetID() string { return this.ID }

// PersonaBindResult reports a persona binding write.
type PersonaBindResult struct {
	// True when the binding was accepted
	Ok bool `json:"ok"`
	// Role name bound
	Role string `json:"role"`
	// Persona assigned to the role
	Persona string `json:"persona"`
}

// PersonaBinding records one role binding for a persona
type PersonaBinding struct {
	// Project identifier containing the binding
	ProjectID string `json:"projectId"`
	// Role name bound to the persona
	Role string `json:"role"`
	// Persona name assigned to the role
	Persona string `json:"persona"`
}

// PersonaConnection is a Relay cursor connection of personas
type PersonaConnection struct {
	// Ordered list of persona edges
	Edges []*PersonaEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of personas matching the filter
	TotalCount int `json:"totalCount"`
}

// PersonaDeleteResult reports a project-local persona delete.
type PersonaDeleteResult struct {
	// True when the persona was deleted
	Ok bool `json:"ok"`
	// Persona name that was deleted
	Name string `json:"name"`
}

// PersonaEdge is one edge in a PersonaConnection
type PersonaEdge struct {
	// The persona at this position
	Node *Persona `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// PhaseTransition records a single phase change event
type PhaseTransition struct {
	// Phase name entered
	Phase string `json:"phase"`
	// Timestamp of the transition
	Ts string `json:"ts"`
	// Sequence number of this phase
	PhaseSeq int `json:"phaseSeq"`
}

// PluginDispatchResult describes the worker started by a plugin action.
type PluginDispatchResult struct {
	// Worker identifier
	ID string `json:"id"`
	// Queued/running state
	State string `json:"state"`
	// Plugin action requested
	Action string `json:"action"`
}

// PluginInfo describes one plugin registry entry.
type PluginInfo struct {
	// Plugin name
	Name string `json:"name"`
	// Registry version
	Version string `json:"version"`
	// Installed version, if present
	InstalledVersion *string `json:"installedVersion,omitempty"`
	// Plugin classification
	Type string `json:"type"`
	// Short description
	Description string `json:"description"`
	// Search keywords
	Keywords []string `json:"keywords"`
	// available, installed, or update-available
	Status string `json:"status"`
	// Registry source
	RegistrySource string `json:"registrySource"`
	// Approximate disk footprint
	DiskBytes int `json:"diskBytes"`
	// Manifest encoded as JSON text
	Manifest *string `json:"manifest,omitempty"`
	// Skill names exposed by the plugin
	Skills []string `json:"skills"`
	// Prompt names exposed by the plugin
	Prompts []string `json:"prompts"`
	// Template names exposed by the plugin
	Templates []string `json:"templates"`
}

// Project represents a registered ddx project on this node
type Project struct {
	// Unique project identifier
	ID string `json:"id"`
	// Short display name
	Name string `json:"name"`
	// Absolute filesystem path to the project root
	Path string `json:"path"`
	// Git remote URL, if configured
	GitRemote *string `json:"gitRemote,omitempty"`
	// When the project was first registered with the server
	RegisteredAt string `json:"registeredAt"`
	// Timestamp of the last successful probe
	LastSeen string `json:"lastSeen"`
	// True when the project path is inaccessible
	Unreachable *bool `json:"unreachable,omitempty"`
	// Set when the project has been tombstoned (soft-deleted)
	TombstonedAt *string `json:"tombstonedAt,omitempty"`
}

func (Project) IsNode() {}

// Globally unique identifier
func (this Project) GetID() string { return this.ID }

// ProjectConnection is a Relay cursor connection of projects
type ProjectConnection struct {
	// Ordered list of project edges
	Edges []*ProjectEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of projects matching the filter
	TotalCount int `json:"totalCount"`
}

// ProjectEdge is one edge in a ProjectConnection
type ProjectEdge struct {
	// The project at this position
	Node *Project `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// Provenance captures host and version metadata for reproducibility
type Provenance struct {
	// Actor that triggered the execution (agent name or "human")
	Actor *string `json:"actor,omitempty"`
	// Hostname where the execution ran
	Host *string `json:"host,omitempty"`
	// Git revision at execution time
	GitRev *string `json:"gitRev,omitempty"`
	// DDx binary version
	DdxVersion *string `json:"ddxVersion,omitempty"`
}

// Provider represents an agent provider/harness configuration
type Provider struct {
	// Unique provider identifier
	ID string `json:"id"`
	// Display name
	Name string `json:"name"`
	// Provider kind (e.g. "cli", "api")
	Kind string `json:"kind"`
	// Default model for this provider
	DefaultModel *string `json:"defaultModel,omitempty"`
	// Available model identifiers
	Models []string `json:"models,omitempty"`
	// Default effort level
	DefaultEffort *string `json:"defaultEffort,omitempty"`
	// Available effort levels
	EffortLevels []string `json:"effortLevels,omitempty"`
	// Default execution timeout in milliseconds
	TimeoutMs *int `json:"timeoutMs,omitempty"`
	// Granted permission scopes
	Permissions []string `json:"permissions,omitempty"`
}

func (Provider) IsNode() {}

// Globally unique identifier
func (this Provider) GetID() string { return this.ID }

// ProviderQuota captures the ceiling reported by the harness/provider, when known.
// All fields are nullable; null means "not reported" (no fabrication).
type ProviderQuota struct {
	// Ceiling tokens for the current window. Null when the harness/provider does not report one.
	CeilingTokens *int `json:"ceilingTokens,omitempty"`
	// Length of the quota window in seconds (e.g. 60 for per-minute ceilings).
	CeilingWindowSeconds *int `json:"ceilingWindowSeconds,omitempty"`
	// Remaining tokens in the current window, as reported by the provider.
	Remaining *int `json:"remaining,omitempty"`
	// RFC3339 timestamp when the quota window resets.
	ResetAt *string `json:"resetAt,omitempty"`
}

// ProviderStatus is the live connectivity status of a configured endpoint provider
// or subprocess harness, mirroring the output of `ddx agent providers` and
// `ddx agent list` / `ddx agent doctor`.
type ProviderStatus struct {
	// Provider/harness name from agent config
	Name string `json:"name"`
	// Kind: endpoint provider or subprocess harness.
	Kind ProviderKind `json:"kind"`
	// Provider type (e.g. "anthropic", "openai-compat") for endpoints; binary name or surface for harnesses.
	ProviderType string `json:"providerType"`
	// API base URL for endpoints; "(subprocess)" for harnesses.
	BaseURL string `json:"baseURL"`
	// Configured model identifier
	Model string `json:"model"`
	// Live connectivity status message
	Status string `json:"status"`
	// True when the last-known status says this endpoint/harness can accept work.
	Reachable bool `json:"reachable"`
	// Human-readable detail explaining the current status.
	Detail string `json:"detail"`
	// Number of models discovered via /v1/models (endpoints) or harness model count (harnesses).
	ModelCount int `json:"modelCount"`
	// True when this is the default provider/harness.
	IsDefault bool `json:"isDefault"`
	// RFC3339 timestamp when health cooldown expires, if on cooldown
	CooldownUntil *string `json:"cooldownUntil,omitempty"`
	// RFC3339 timestamp of the last probe result (cached or live).
	LastCheckedAt *string `json:"lastCheckedAt,omitempty"`
	// Rolling usage aggregated from the sessions index. Null when sessions index is unavailable.
	Usage *ProviderUsage `json:"usage,omitempty"`
	// Quota ceiling + reset from the harness/provider. Null when unreported.
	Quota *ProviderQuota `json:"quota,omitempty"`
	// Profile names where this row is the default candidate (may be empty).
	DefaultForProfile []string `json:"defaultForProfile"`
}

// ProviderTrend is the trend-detail payload for `/providers/[name]`.
type ProviderTrend struct {
	// Provider/harness name.
	Name string `json:"name"`
	// Endpoint vs harness.
	Kind ProviderKind `json:"kind"`
	// Window in days covered by series points.
	WindowDays int `json:"windowDays"`
	// Time-bucketed usage points, oldest first.
	Series []*ProviderTrendPoint `json:"series"`
	// Quota ceiling tokens; null when unreported.
	CeilingTokens *int `json:"ceilingTokens,omitempty"`
	// Projected hours until the ceiling is hit, computed from the last-24h slope. Null when ceiling is unreported or slope is non-positive.
	ProjectedRunOutHours *float64 `json:"projectedRunOutHours,omitempty"`
}

// ProviderTrendPoint is one time-bucketed data point of usage vs. ceiling.
type ProviderTrendPoint struct {
	// RFC3339 bucket start (hour-aligned for ≤7d windows, 4-hour-aligned beyond).
	BucketStart string `json:"bucketStart"`
	// Sum of tokens recorded in sessions whose StartedAt falls in this bucket.
	Tokens int `json:"tokens"`
	// Count of sessions in this bucket.
	Requests int `json:"requests"`
}

// ProviderUsage is a rolling-window token/request summary computed from the sessions index.
type ProviderUsage struct {
	// Tokens recorded in sessions whose StartedAt falls in the last 60 minutes. Null when unavailable.
	TokensUsedLastHour *int `json:"tokensUsedLastHour,omitempty"`
	// Tokens recorded in sessions whose StartedAt falls in the last 24 hours. Null when unavailable.
	TokensUsedLast24h *int `json:"tokensUsedLast24h,omitempty"`
	// Session count in the last 60 minutes. Null when unavailable.
	RequestsLastHour *int `json:"requestsLastHour,omitempty"`
	// Session count in the last 24 hours. Null when unavailable.
	RequestsLast24h *int `json:"requestsLast24h,omitempty"`
}

// Query is the root entry point for all read operations
type Query struct {
}

// QueueAndWorkersSummary backs the global drain indicator. Combines the
// ready-bead count with running/total worker counts so the NavShell badge
// can render without issuing two queries per poll.
type QueueAndWorkersSummary struct {
	// Open beads with no unmet dependencies (the drain queue depth)
	ReadyBeads int `json:"readyBeads"`
	// Count of workers in state `running` for this project
	RunningWorkers int `json:"runningWorkers"`
	// Total workers on record for this project (any state)
	TotalWorkers int `json:"totalWorkers"`
}

// QueueSummary is a compact project queue status for action dispatch.
type QueueSummary struct {
	// Open beads with no unmet dependencies
	Ready int `json:"ready"`
	// Open beads blocked by unmet dependencies
	Blocked int `json:"blocked"`
	// Beads currently claimed or executing
	InProgress int `json:"inProgress"`
}

// ReadyCheck represents one subsystem readiness check
type ReadyCheck struct {
	// Subsystem name being checked
	Name string `json:"name"`
	// Check result ("ok" or a short problem description)
	Status string `json:"status"`
}

// ReadyStatus represents the server readiness response
type ReadyStatus struct {
	// True when all subsystem checks pass
	Ready bool `json:"ready"`
	// Per-subsystem readiness state
	Checks []*ReadyCheck `json:"checks"`
}

// ResultSpec describes how to interpret an execution result
type ResultSpec struct {
	// Metric-shaped projection (null if not metric-typed)
	Metric *MetricResultSpec `json:"metric,omitempty"`
}

// ReworkReport describes reopen and post-close churn over a time window
type ReworkReport struct {
	// Report scope
	Scope string `json:"scope"`
	// Time window for the report
	Window *Window `json:"window,omitempty"`
	// Per-bead rework rows
	Beads []*ReworkRow `json:"beads,omitempty"`
	// Aggregate rework summary
	Summary *ReworkSummary `json:"summary"`
}

// ReworkRow describes reopen and revision facts for one bead
type ReworkRow struct {
	// Bead identifier
	BeadID string `json:"beadId"`
	// Bead title
	Title string `json:"title"`
	// Spec/feature ID the bead belongs to
	SpecID *string `json:"specId,omitempty"`
	// Current bead status
	Status string `json:"status"`
	// When the bead was first closed
	FirstClosedAt *string `json:"firstClosedAt,omitempty"`
	// Whether the bead has been reopened at least once
	Reopened bool `json:"reopened"`
	// Number of times the bead was reopened
	ReopenCount *int `json:"reopenCount,omitempty"`
	// Number of post-close revisions
	RevisionCount *int `json:"revisionCount,omitempty"`
	// Rework data quality: known, estimated, or unknown
	ReworkState string `json:"reworkState"`
	// Source references for rework attribution
	Provenance []*SourceRef `json:"provenance,omitempty"`
}

// ReworkSummary aggregates reopen and post-close churn
type ReworkSummary struct {
	// Number of beads with known closure data
	KnownClosed int `json:"knownClosed"`
	// Number of beads known to have been reopened
	KnownReopened int `json:"knownReopened"`
	// Number of beads with unknown rework data
	UnknownCount int `json:"unknownCount"`
	// Ratio of reopened to total closed beads
	ReopenRate float64 `json:"reopenRate"`
	// Total number of post-close revisions
	RevisionCount int `json:"revisionCount"`
}

// SearchResult represents a single search hit from the library
type SearchResult struct {
	// Filesystem path of the matching resource
	Path string `json:"path"`
	// Resource type (e.g. "prompt", "template", "persona")
	Type string `json:"type"`
	// Display name of the resource
	Name string `json:"name"`
	// Excerpt showing the match context
	Snippet *string `json:"snippet,omitempty"`
}

// SearchResultConnection is a Relay cursor connection of search results
type SearchResultConnection struct {
	// Ordered list of search result edges
	Edges []*SearchResultEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of results matching the query
	TotalCount int `json:"totalCount"`
}

// SearchResultEdge is one edge in a SearchResultConnection
type SearchResultEdge struct {
	// The search result at this position
	Node *SearchResult `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// SessionsCostSummary separates cash, subscription-equivalent, and local session costs
type SessionsCostSummary struct {
	// Actual billed pay-per-token API spend
	CashUsd float64 `json:"cashUsd"`
	// Dollar-equivalent token value consumed under subscription harnesses
	SubscriptionEquivUsd float64 `json:"subscriptionEquivUsd"`
	// Count of sessions served locally
	LocalSessionCount int `json:"localSessionCount"`
	// Optional local compute estimate, present only when configured
	LocalEstimatedUsd *float64 `json:"localEstimatedUsd,omitempty"`
}

// SourceRef explains where a derived metric fact originated
type SourceRef struct {
	// Bead ID associated with this fact
	BeadID *string `json:"beadId,omitempty"`
	// Agent session ID associated with this fact
	SessionID *string `json:"sessionId,omitempty"`
	// Native (harness-specific) session identifier
	NativeSessionID *string `json:"nativeSessionId,omitempty"`
	// Native log reference for traceability
	NativeLogRef *string `json:"nativeLogRef,omitempty"`
	// SHA of the commit that closed the bead
	ClosingCommitSha *string `json:"closingCommitSha,omitempty"`
	// Timestamp of the source event
	Timestamp *string `json:"timestamp,omitempty"`
	// Source system identifier
	Source *string `json:"source,omitempty"`
}

// StaleReason explains why a specific document is stale
type StaleReason struct {
	// Document identifier
	ID string `json:"id"`
	// Filesystem path of the stale document
	Path string `json:"path"`
	// Human-readable explanations of why the document is stale
	Reasons []string `json:"reasons"`
}

// StartWorkerInput configures a project execute-loop worker.
type StartWorkerInput struct {
	// Project identifier
	ProjectID string `json:"projectId"`
	// Optional harness override
	Harness *string `json:"harness,omitempty"`
	// Routing profile, defaulting to smart when omitted
	Profile *string `json:"profile,omitempty"`
	// Reasoning effort, defaulting to medium when omitted
	Effort *string `json:"effort,omitempty"`
	// Optional label filter for ready beads
	LabelFilter *string `json:"labelFilter,omitempty"`
}

// Subscription is the root entry point for all real-time events
type Subscription struct {
}

// Thresholds captures the ratchet policy for metric evaluations
type Thresholds struct {
	// Warn threshold in milliseconds
	WarnMs *float64 `json:"warnMs,omitempty"`
	// Ratchet threshold in milliseconds
	RatchetMs *float64 `json:"ratchetMs,omitempty"`
}

// TokenUsage breaks down token consumption for a session
type TokenUsage struct {
	// Number of prompt/input tokens consumed
	Prompt *int `json:"prompt,omitempty"`
	// Number of completion/output tokens generated
	Completion *int `json:"completion,omitempty"`
	// Total tokens (prompt + completion)
	Total *int `json:"total,omitempty"`
	// Number of tokens served from cache
	Cached *int `json:"cached,omitempty"`
}

// Window captures the time window used to scope a metrics query
type Window struct {
	// Cutoff time for the window (null means all-time)
	Since *string `json:"since,omitempty"`
}

// Worker represents an execute-loop worker process
type Worker struct {
	// Unique worker identifier
	ID string `json:"id"`
	// Worker kind (e.g. "execute-loop")
	Kind string `json:"kind"`
	// Current lifecycle state (e.g. "running", "idle", "stopped")
	State string `json:"state"`
	// Human-readable status summary
	Status *string `json:"status,omitempty"`
	// Absolute path to the project this worker operates on
	ProjectRoot string `json:"projectRoot"`
	// Agent harness name (e.g. "claude", "codex")
	Harness *string `json:"harness,omitempty"`
	// Provider/backend name
	Provider *string `json:"provider,omitempty"`
	// Model identifier used for execution
	Model *string `json:"model,omitempty"`
	// Effort level (e.g. "low", "medium", "high")
	Effort *string `json:"effort,omitempty"`
	// True if the worker should stop after one bead
	Once *bool `json:"once,omitempty"`
	// Interval between poll cycles (e.g. "30s")
	PollInterval *string `json:"pollInterval,omitempty"`
	// When the worker was started
	StartedAt *string `json:"startedAt,omitempty"`
	// When the worker finished (null if still running)
	FinishedAt *string `json:"finishedAt,omitempty"`
	// Fatal error that stopped the worker
	Error *string `json:"error,omitempty"`
	// Path to the worker's stdout log file
	StdoutPath *string `json:"stdoutPath,omitempty"`
	// Path to the worker's spec/config file
	SpecPath *string `json:"specPath,omitempty"`
	// Total number of execution attempts
	Attempts *int `json:"attempts,omitempty"`
	// Number of successful executions
	Successes *int `json:"successes,omitempty"`
	// Number of failed executions
	Failures *int `json:"failures,omitempty"`
	// Bead ID currently being executed (null if idle)
	CurrentBead *string `json:"currentBead,omitempty"`
	// Most recent error message from an execution
	LastError *string `json:"lastError,omitempty"`
	// Result of the most recently completed execution
	LastResult *WorkerExecutionResult `json:"lastResult,omitempty"`
	// In-flight attempt summary (null if idle)
	CurrentAttempt *CurrentAttemptInfo `json:"currentAttempt,omitempty"`
	// Recent phase transitions for observability
	RecentPhases []*PhaseTransition `json:"recentPhases,omitempty"`
	// Summary of the most recently completed attempt
	LastAttempt *LastAttemptInfo `json:"lastAttempt,omitempty"`
	// Land coordinator metrics for this worker's project
	LandSummary *CoordinatorMetrics `json:"landSummary,omitempty"`
	// Recent streamed response events captured for the worker detail view
	RecentEvents []*WorkerRecentEvent `json:"recentEvents"`
	// Operator lifecycle actions recorded for this worker
	LifecycleEvents []*WorkerLifecycleEvent `json:"lifecycleEvents"`
}

func (Worker) IsNode() {}

// Globally unique identifier
func (this Worker) GetID() string { return this.ID }

// WorkerConnection is a Relay cursor connection of workers
type WorkerConnection struct {
	// Ordered list of worker edges
	Edges []*WorkerEdge `json:"edges"`
	// Pagination metadata
	PageInfo *PageInfo `json:"pageInfo"`
	// Total number of workers matching the filter
	TotalCount int `json:"totalCount"`
}

// WorkerDispatchResult describes the worker started by an action.
type WorkerDispatchResult struct {
	// Worker identifier
	ID string `json:"id"`
	// Queued/running state
	State string `json:"state"`
	// Worker kind
	Kind string `json:"kind"`
}

// WorkerEdge is one edge in a WorkerConnection
type WorkerEdge struct {
	// The worker at this position
	Node *Worker `json:"node"`
	// Opaque cursor for pagination
	Cursor string `json:"cursor"`
}

// WorkerEvent is a progress or lifecycle event from a worker
type WorkerEvent struct {
	// Unique event identifier
	EventID string `json:"eventID"`
	// Worker that emitted this event
	WorkerID string `json:"workerID"`
	// Current execution phase (e.g. "pending", "running", "done")
	Phase string `json:"phase"`
	// Timestamp of the event
	Timestamp string `json:"timestamp"`
	// Log line output from the worker (if any)
	LogLine *string `json:"logLine,omitempty"`
	// Bead ID being executed (null if not executing a bead)
	BeadID *string `json:"beadID,omitempty"`
}

// WorkerExecutionResult captures the outcome of one execution
type WorkerExecutionResult struct {
	// Bead that was executed
	BeadID *string `json:"beadId,omitempty"`
	// Unique attempt identifier
	AttemptID *string `json:"attemptId,omitempty"`
	// Worker that ran the execution
	WorkerID *string `json:"workerId,omitempty"`
	// Harness used
	Harness *string `json:"harness,omitempty"`
	// Provider used
	Provider *string `json:"provider,omitempty"`
	// Model used
	Model *string `json:"model,omitempty"`
	// Outcome status (e.g. "success", "failure", "timeout")
	Status *string `json:"status,omitempty"`
	// Human-readable outcome detail
	Detail *string `json:"detail,omitempty"`
	// Correlated agent session ID
	SessionID *string `json:"sessionId,omitempty"`
	// Git revision the execution started from
	BaseRev *string `json:"baseRev,omitempty"`
	// Git revision produced by the execution
	ResultRev *string `json:"resultRev,omitempty"`
	// Suggested retry delay (e.g. "30s")
	RetryAfter *string `json:"retryAfter,omitempty"`
}

// WorkerLifecycleEvent records an operator lifecycle action.
type WorkerLifecycleEvent struct {
	// Action name, such as start or stop
	Action string `json:"action"`
	// Actor identifier known to the server
	Actor string `json:"actor"`
	// When the action was recorded
	Timestamp string `json:"timestamp"`
	// Optional action detail
	Detail *string `json:"detail,omitempty"`
	// Bead involved in the action, if any
	BeadID *string `json:"beadId,omitempty"`
}

// WorkerLifecycleResult describes a lifecycle mutation result.
type WorkerLifecycleResult struct {
	// Worker identifier
	ID string `json:"id"`
	// Worker state after the mutation was accepted
	State string `json:"state"`
	// Worker kind
	Kind string `json:"kind"`
}

// WorkerLog holds captured output from a worker process
type WorkerLog struct {
	// Captured standard output
	Stdout string `json:"stdout"`
	// Captured standard error
	Stderr string `json:"stderr"`
}

// WorkerRecentEvent is one captured response frame in worker detail history
type WorkerRecentEvent struct {
	// Event kind: text_delta or tool_call
	Kind string `json:"kind"`
	// Text content for text_delta events
	Text *string `json:"text,omitempty"`
	// Tool name for tool_call events
	Name *string `json:"name,omitempty"`
	// Tool call input payload encoded as JSON text
	Inputs *string `json:"inputs,omitempty"`
	// Tool call output text
	Output *string `json:"output,omitempty"`
}

// ProviderKind distinguishes endpoint providers from subprocess harnesses.
type ProviderKind string

const (
	// API-endpoint provider configured via base URL + key (e.g. anthropic, openai-compat).
	ProviderKindEndpoint ProviderKind = "ENDPOINT"
	// Subprocess harness invoked via a local binary (e.g. claude, codex, gemini).
	ProviderKindHarness ProviderKind = "HARNESS"
)

var AllProviderKind = []ProviderKind{
	ProviderKindEndpoint,
	ProviderKindHarness,
}

func (e ProviderKind) IsValid() bool {
	switch e {
	case ProviderKindEndpoint, ProviderKindHarness:
		return true
	}
	return false
}

func (e ProviderKind) String() string {
	return string(e)
}

func (e *ProviderKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProviderKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProviderKind", str)
	}
	return nil
}

func (e ProviderKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProviderKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProviderKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
